# Configuration Jekyll pour Portfolio Joachim Douillard
title: Joachim Douillard - Portfolio
description: Portfolio de Joachim Douillard - Développeur Web & Logiciel, Technicien IT
baseurl: ""
url: "" # Sera défini automatiquement par Netlify

# Configuration Jekyll
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections et dossiers
sass:
  sass_dir: _sass
  style: compressed

# Exclusions
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Variables personnalisées pour le portfolio
author:
  name: "Joachim Douillard"
  titles:
    - "IT technician"
    - "Web developer" 
    - "Software developer"
  github: "https://github.com/JoaDouillard?tab=repositories"
  linkedin: "https://www.linkedin.com/in/joachim-douillard"
  status: "Currently Available"
  response_time: "< 24h"

# Couleurs du thème (reprises de l'ancien portfolio)
theme:
  colors:
    bg_color: "#0a192f"
    text_color: "#8892b0"
    highlight_color: "#64ffda"
    red_color: "#ff6b6b"
    blue_color: "#818cf8"

# Navigation principale
navigation:
  - name: "about"
    url: "/about"
    title: "À propos"
  - name: "skills"
    url: "/skills" 
    title: "Compétences"
  - name: "contact"
    url: "/contact"
    title: "Contact"
  - name: "projects"
    url: "/projects"
    title: "Projets"

# Configuration des projets (reprises des données de l'ancien portfolio)
projects:
  - id: 1
    title: "Projet Symfony"
    description: "Symfony est une plateforme permettant aux utilisateurs de consulter, gérer et s'inscrire à des événements musicaux."
    image: "/assets/images/projects/project1/VignetteP1.webp"
    demo_video: "/assets/images/projects/project1/DemoP1.webm"
    details_video: "/assets/images/projects/project1/DetailsP1.webm"
    link_text: "Voir mon travail >"
    
  - id: 2
    title: "Project 2"
    description: "Description détaillée du projet 2. Technologies utilisées et objectifs atteints."
    image: "/assets/images/projects/project2/DetailsP2.svg"
    demo_video: "/assets/images/projects/project2/DemoP2.webm"
    link_text: "Regardez le résultat >"
    
  - id: 3
    title: "Project 3"
    description: "Description du projet 3 avec les technologies et fonctionnalités implémentées."
    image: "/assets/images/projects/project3/VignetteP3.webp"
    demo_video: "/assets/images/projects/project3/DemoP3.webm"
    details_image: "/assets/images/projects/project3/DetailsP3.webp"
    
  - id: 4
    title: "Project 4"
    description: "Description du projet 4 et de ses spécificités techniques."
    image: "/assets/images/projects/project4/VignetteP4.webp"